# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=155, verbose_name='用户微信id')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('product_desc', models.CharField(max_length=200, verbose_name='商品描述')),
                ('product_price', models.IntegerField(default=0, verbose_name='商品价格')),
                ('order_status', models.IntegerField(default=1, verbose_name='订单状态')),
                ('img_url', models.CharField(max_length=155, verbose_name='图片地址')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='商品ID')),
                ('product_name', models.CharField(default='', max_length=200, verbose_name='商品名称')),
                ('product_price', models.IntegerField(default=0, verbose_name='商品价格')),
                ('product_desc', models.CharField(default='', max_length=1000, verbose_name='商品信息')),
                ('product_img_url', models.CharField(default='', max_length=255, verbose_name='图片地址')),
                ('product_address', models.CharField(default='', max_length=200, verbose_name='服务地址')),
                ('service_type', models.CharField(default='', max_length=200, verbose_name='服务方式：在线')),
                ('service_address', models.CharField(default='', max_length=200, verbose_name='服务范围：北京')),
                ('service_way', models.CharField(default='', max_length=200, verbose_name='服务期限')),
                ('service_time', models.CharField(default='', max_length=200, verbose_name='办理时间')),
            ],
        ),
        migrations.CreateModel(
            name='SavedProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=155, verbose_name='用户微信id')),
                ('saved_product_id', models.IntegerField(verbose_name='商品ID')),
            ],
        ),
        migrations.CreateModel(
            name='SessionOpenId',
            fields=[
                ('trd_session', models.CharField(max_length=256, verbose_name='3rd_session')),
                ('session_key', models.CharField(max_length=256, verbose_name='session_key')),
                ('openId', models.CharField(max_length=256, verbose_name='用户唯一标识')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(verbose_name='注册时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=155, verbose_name='用户微信id')),
                ('user_wechat_name', models.CharField(max_length=155, verbose_name='用户微信昵称')),
                ('user_img_url', models.CharField(default='', max_length=255, verbose_name='用户微信头像')),
                ('name', models.CharField(default='', max_length=255, verbose_name='用户姓名')),
                ('phone', models.CharField(default='', max_length=15, verbose_name='用户手机号')),
                ('email', models.CharField(default='', max_length=255, verbose_name='用户邮箱')),
                ('address', models.CharField(default='', max_length=255, verbose_name='用户通信地址')),
            ],
        ),
    ]
