# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ylawyer', '0002_auto_20171029_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='out_trade_show_no',
            field=models.CharField(default='0', max_length=155, verbose_name='微信订单号'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='out_trade_no',
            field=models.CharField(default='0', max_length=155, verbose_name='微信订单支付号'),
        ),
    ]
