# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ylawyer', '0004_orderlist_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='time',
            field=models.DateTimeField(verbose_name='下单时间'),
        ),
    ]
