# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ylawyer', '0008_auto_20171112_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='product_dimension',
            field=models.CharField(default='份', max_length=50, verbose_name='产品单位'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='product_pic_url',
            field=models.CharField(default='', max_length=255, verbose_name='展览页图片地址'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='tab_id',
            field=models.CharField(default='1', max_length=20, verbose_name='商品分类ID'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='tab_img_url',
            field=models.CharField(default='', max_length=200, verbose_name='导航图地址'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='tab_name',
            field=models.CharField(default='', max_length=200, verbose_name='商品分类'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='product_img_url',
            field=models.CharField(default='', max_length=255, verbose_name='详情页图片地址'),
        ),
    ]
